---
galaxy_info:
  author: DevOps Team
  description: Rolle zum Herunterladen und Installieren von RPM-Paketen von GitHub auf Oracle Linux
  company: Your Company

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: OracleLinux
      versions:
        - 7
        - 8
        - 9
    - name: EL
      versions:
        - 7
        - 8
        - 9

  galaxy_tags:
    - rpm
    - oracle
    - linux
    - github
    - deployment
    - package

dependencies: []
