---
# Standard-Variablen für die rpm_install Rolle

# Verzeichnis für RPM-Download
rpm_download_dir: /opt/tmp

# Benutzer und Gruppe für Berechtigungen
rpm_owner: apps
rpm_group: apps

# RPM-Datei Name
rpm_filename: application.rpm

# GitHub Download URL wird dynamisch erstellt
rpm_state: present  # present oder latest
