---
galaxy_info:
  author: Network Traffic Logger
  description: Ansible role for deploying Network Traffic Logger
  company:
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - networking
    - monitoring
    - netflow
    - traffic
    - docker

dependencies: []
